name: "HTML5 Validator"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.1
        with:
          root: /
          css: true
        continue-on-error: true
      - name: Push to released Repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: log.log
          destination-github-username: 'mrepol742'
          destination-repository-name: 'mrepol742.github.io'
          user-email: mrepol742@gmail.com
          commit-message: Initial Commit
          target-branch: master
          target-directory: log
