name: "Webvium Minification"

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11.0.10
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.10

      - name: Clone Git Repository
        run: git clone https://github.com/mrepol742/mrepol742.github.io
      - name: Run
        run: java Main
      
      - name: Push to released Repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: mrepol742.github.io
          destination-github-username: 'mrepol742'
          destination-repository-name: 'mrepol742.github.io'
          user-email: mrepol742@gmail.com
          commit-message: Initial Commit
          target-branch: master
